# Script to create a new GitHub repository with complete branch structure
# Creates: GitHub repo, README, .gitignore, develop and release branches
# Sets default branch to develop

param(
    [Parameter(Mandatory=$true)]
    [string]$RepoName,
    
    [string]$Organization = "wtw-RiskTechnology",
    [string]$DevelopBranchName = "develop",
    [string]$ReleaseBranchName = "release",
    [ValidateSet("internal", "private", "public")]
    [string]$Visibility = "internal",
    [string]$Description = "",
    [string]$ProtectedEnvReviewerTeam = "release-approvers"
)

$ErrorActionPreference = 'Stop'

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "GitHub Repository Creation Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Organization: $Organization" -ForegroundColor White
Write-Host "Repository: $RepoName" -ForegroundColor White
Write-Host "Visibility: $Visibility" -ForegroundColor White
Write-Host ""

# Check if GitHub CLI is installed
Write-Host "Checking for GitHub CLI..." -ForegroundColor Yellow
$ghInstalled = Get-Command gh -ErrorAction SilentlyContinue

if (-not $ghInstalled) {
    Write-Error "GitHub CLI (gh) is required but not found. Please install it from https://cli.github.com/"
    exit 1
}
Write-Host "✓ GitHub CLI found" -ForegroundColor Green

# Check GitHub CLI authentication
Write-Host "`nVerifying GitHub authentication..." -ForegroundColor Yellow
try {
    $authStatus = gh auth status 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Not authenticated with GitHub CLI. Please run 'gh auth login' first."
        exit 1
    }
    Write-Host "✓ Authenticated with GitHub" -ForegroundColor Green
}
catch {
    Write-Error "GitHub authentication check failed: $_"
    exit 1
}

# Save original working directory
$originalLocation = Get-Location

# Create temporary directory for repo
$tempDir = Join-Path $env:TEMP $RepoName
if (Test-Path $tempDir) {
    Write-Host "`nRemoving existing temporary directory..." -ForegroundColor Yellow
    Remove-Item -Path $tempDir -Recurse -Force
}

New-Item -Path $tempDir -ItemType Directory -Force | Out-Null
Set-Location $tempDir
Write-Host "✓ Created temporary directory: $tempDir" -ForegroundColor Green

# Initialize git repository
Write-Host "`nInitializing git repository..." -ForegroundColor Yellow
git init
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to initialize git repository"
    exit 1
}
git checkout -b main
Write-Host "✓ Git repository initialized" -ForegroundColor Green

# Create README.md
Write-Host "`nCreating README.md..." -ForegroundColor Yellow
$readmeContent = "# $RepoName"
Set-Content -Path "README.md" -Value $readmeContent -Encoding UTF8
Write-Host "✓ README.md created" -ForegroundColor Green

# Download Visual Studio .gitignore
Write-Host "`nCreating Visual Studio .gitignore..." -ForegroundColor Yellow
try {
    $gitignoreUrl = "https://raw.githubusercontent.com/github/gitignore/main/VisualStudio.gitignore"
    $gitignoreContent = Invoke-WebRequest -Uri $gitignoreUrl -UseBasicParsing
    Set-Content -Path ".gitignore" -Value $gitignoreContent.Content -Encoding UTF8
    Write-Host "✓ .gitignore created" -ForegroundColor Green
}
catch {
    Write-Warning "Failed to download .gitignore template: $_"
    Write-Host "Creating basic .gitignore..." -ForegroundColor Yellow
    
    $basicGitignore = @"
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/

# Visual Studio cache/options directory
.vs/

# MSTest test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

# NuGet Packages
*.nupkg
*.snupkg
**/packages/*
!**/packages/build/
*.nuget.props
*.nuget.targets

# Visual Studio cache files
*.cache
*.cachefile

# Others
*.log
*.vspscc
*.vssscc
.builds
"@
    Set-Content -Path ".gitignore" -Value $basicGitignore -Encoding UTF8
    Write-Host "✓ Basic .gitignore created" -ForegroundColor Green
}

# Initial commit
Write-Host "`nCreating initial commit..." -ForegroundColor Yellow
git add .
git commit -m "Initial commit with README and .gitignore"
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to create initial commit"
    exit 1
}
Write-Host "✓ Initial commit created" -ForegroundColor Green

# Create GitHub repository
Write-Host "`nCreating GitHub repository in organization '$Organization'..." -ForegroundColor Yellow
$fullRepoName = "$Organization/$RepoName"
$visibilityFlag = "--$Visibility"
$descParam = if ($Description) { "--description `"$Description`"" } else { "" }

try {
    if ($Description) {
        gh repo create $fullRepoName $visibilityFlag --source=. --remote=origin --description $Description
    }
    else {
        gh repo create $fullRepoName $visibilityFlag --source=. --remote=origin
    }
    
    if ($LASTEXITCODE -ne 0) {
        throw "GitHub repo creation failed"
    }
    Write-Host "✓ GitHub repository created" -ForegroundColor Green
}
catch {
    Write-Error "Failed to create GitHub repository: $_"
    exit 1
}

# Push main branch
Write-Host "`nPushing main branch to remote..." -ForegroundColor Yellow
git push -u origin main
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to push main branch"
    exit 1
}
Write-Host "✓ Main branch pushed" -ForegroundColor Green

# Create develop branch from main
Write-Host "`nCreating '$DevelopBranchName' branch from main..." -ForegroundColor Yellow
git checkout -b $DevelopBranchName
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to create develop branch"
    exit 1
}
Write-Host "✓ Created '$DevelopBranchName' branch" -ForegroundColor Green

# Push develop branch to remote
Write-Host "Pushing '$DevelopBranchName' branch to origin..." -ForegroundColor Yellow
git push -u origin $DevelopBranchName
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to push develop branch"
    exit 1
}
Write-Host "✓ Pushed '$DevelopBranchName' to remote" -ForegroundColor Green

# Create release branch from develop
Write-Host "`nCreating '$ReleaseBranchName' branch from $DevelopBranchName..." -ForegroundColor Yellow
git checkout -b $ReleaseBranchName
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to create release branch"
    exit 1
}
Write-Host "✓ Created '$ReleaseBranchName' branch" -ForegroundColor Green

# Push release branch to remote
Write-Host "Pushing '$ReleaseBranchName' branch to origin..." -ForegroundColor Yellow
git push -u origin $ReleaseBranchName
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to push release branch"
    exit 1
}
Write-Host "✓ Pushed '$ReleaseBranchName' to remote" -ForegroundColor Green

# Set default branch to develop
Write-Host "`nSetting default branch to '$DevelopBranchName'..." -ForegroundColor Yellow
$repoPath = ""
try {
    # Get the repository name (gh repo create uses format owner/repo)
    $remoteUrl = git remote get-url origin
    
    # Extract owner/repo from the URL
    if ($remoteUrl -match 'github\.com[:/](.+/.+?)(\.git)?$') {
        $repoPath = $matches[1] -replace '\.git$', ''
        
        Write-Host "Updating default branch for repository: $repoPath" -ForegroundColor Gray
        
        # Set default branch using GitHub CLI
        gh repo edit $repoPath --default-branch $DevelopBranchName 2>&1 | Out-Null
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "✓ Default branch set to '$DevelopBranchName'" -ForegroundColor Green
        }
        else {
            Write-Warning "Failed to set default branch. You may need to set it manually in GitHub settings."
        }
    }
    else {
        Write-Warning "Could not parse repository name from remote URL: $remoteUrl"
    }
}
catch {
    Write-Warning "Could not set default branch: $_"
    Write-Host "  You can manually set the default branch in GitHub repository settings." -ForegroundColor Gray
}

# Create copilot-ready label
Write-Host "`nConfiguring repository labels..." -ForegroundColor Yellow
# --force updates the label if it already exists, so this step is safe to re-run
gh label create "copilot-ready" `
    --color "0075ca" `
    --description "Issue is fully specified; safe to assign to Copilot" `
    --repo $fullRepoName `
    --force

if ($LASTEXITCODE -ne 0) {
    Write-Warning "Failed to create 'copilot-ready' label. You can create it manually in GitHub repository settings."
}
else {
    Write-Host "✓ Label 'copilot-ready' created" -ForegroundColor Green
}

# Configure repo-level OIDC subject customization
Write-Host "`nConfiguring repo-level OIDC subject customization..." -ForegroundColor Yellow
$repoOidcBody = '{"use_default":false,"include_claim_keys":["repository_owner","environment"]}'
$oidcResult = $repoOidcBody | gh api "repos/$Organization/$RepoName/actions/oidc/customization/sub" --method PUT --input - 2>&1

if ($LASTEXITCODE -ne 0) {
    Write-Warning "Failed to set OIDC subject customization: $oidcResult"
    Write-Host "  You can run .\GitHub\setupFederatedCredentials_step3_singleRepo.ps1 -RepoName $RepoName" -ForegroundColor Gray
}
else {
    Write-Host "✓ OIDC subject set to [repository_owner, environment]" -ForegroundColor Green
}

# Create and protect deployment environments
Write-Host "`nConfiguring deployment environments..." -ForegroundColor Yellow

$unprotectedEnvs = @("DEV", "QA")
$protectedEnvs   = @("RC", "IAT", "PROD")

# Resolve the reviewer team ID (needed for protected envs)
$reviewerPayload = $null
$teamResponse = gh api "/orgs/$Organization/teams/$ProtectedEnvReviewerTeam" 2>&1
if ($LASTEXITCODE -eq 0) {
    $teamId = ($teamResponse | ConvertFrom-Json).id
    $reviewerPayload = @{
        reviewers = @(@{ type = "Team"; id = $teamId })
    } | ConvertTo-Json -Depth 5 -Compress
}
else {
    Write-Warning "Could not resolve team '$ProtectedEnvReviewerTeam' (exit $LASTEXITCODE). Protected environments will be created without required reviewers."
}

foreach ($env in $unprotectedEnvs) {
    $emptyBody = '{}'
    $result = $emptyBody | gh api --method PUT "/repos/$Organization/$RepoName/environments/$env" --input - 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  ✓ Environment '$env' created" -ForegroundColor Green
    } else {
        Write-Warning "  Failed to create environment '$env': $result"
    }
}

foreach ($env in $protectedEnvs) {
    $body = if ($reviewerPayload) { $reviewerPayload } else { '{}' }
    $result = $body | gh api --method PUT "/repos/$Organization/$RepoName/environments/$env" --input - 2>&1
    if ($LASTEXITCODE -eq 0) {
        $suffix = if ($reviewerPayload) { " (required reviewer: $ProtectedEnvReviewerTeam)" } else { "" }
        Write-Host "  ✓ Environment '$env' created$suffix" -ForegroundColor Green
    } else {
        Write-Warning "  Failed to create environment '$env': $result"
    }
}

# Navigate back to original directory and clean up temp directory
Write-Host "`nCleaning up temporary directory..." -ForegroundColor Yellow
Set-Location $originalLocation
if (Test-Path $tempDir) {
    Remove-Item -Path $tempDir -Recurse -Force
}
Write-Host "✓ Temporary directory cleaned up" -ForegroundColor Green

# Clone the repository to current directory
Write-Host "`nCloning repository to current directory..." -ForegroundColor Yellow
try {
    gh repo clone $repoPath
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to clone repository"
    }
    Write-Host "✓ Repository cloned" -ForegroundColor Green
}
catch {
    Write-Error "Failed to clone repository: $_"
    exit 1
}

# Change into the cloned repository directory
$repoFolder = $RepoName
Set-Location $repoFolder
Write-Host "✓ Changed to repository directory: $(Get-Location)" -ForegroundColor Green

# Switch to develop branch
Write-Host "`nSwitching to '$DevelopBranchName' branch..." -ForegroundColor Yellow
git checkout $DevelopBranchName
Write-Host "✓ On '$DevelopBranchName' branch" -ForegroundColor Green

# Scaffold docs/adr/
Write-Host "`nScaffolding docs/adr/..." -ForegroundColor Yellow
New-Item -Path "docs/adr" -ItemType Directory -Force | Out-Null
$adrReadme = @"
# Architecture Decision Records

Service-specific Architecture Decision Records for $RepoName.

For org-wide ADRs (e.g. DefaultAzureCredential, Parquet snappy codec) see:
https://github.com/wtw-RiskTechnology/rna-standards/tree/develop/docs/adr

## Creating a new ADR

1. Pick the next sequential number in this folder
2. Name the file ``NNNN-short-hyphenated-title.md``
3. Use the template from the org-wide ADR README

Numbers are local to this repository and independent of org-wide ADR numbers.
"@
Set-Content -Path "docs/adr/README.md" -Value $adrReadme.TrimStart() -Encoding UTF8

git add "docs/adr/README.md"
git commit -m "chore: scaffold docs/adr directory"
git push

if ($LASTEXITCODE -ne 0) {
    Write-Warning "Failed to push docs/adr scaffold. You can create it manually."
}
else {
    Write-Host "✓ docs/adr/ scaffolded and pushed" -ForegroundColor Green
}

# Display summary
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "Repository Setup Complete!" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

Write-Host "`nRepository location: $(Get-Location)" -ForegroundColor White

Write-Host "`nBranches created:" -ForegroundColor Yellow
git branch

Write-Host "`nRemote branches:" -ForegroundColor Yellow
git branch -r

Write-Host "`nBranch Structure:" -ForegroundColor Cyan
Write-Host "  main" -ForegroundColor Green
Write-Host "   └─> $DevelopBranchName (default)" -ForegroundColor Green
Write-Host "        └─> $ReleaseBranchName" -ForegroundColor Green

# Get repository URL
$repoUrl = gh repo view --json url --jq .url 2>$null
if ($repoUrl) {
    Write-Host "`nRepository URL: $repoUrl" -ForegroundColor Cyan
}

Write-Host "`nEnvironments created:" -ForegroundColor Yellow
Write-Host "  DEV, QA          (no protection)" -ForegroundColor Gray
Write-Host "  RC, IAT, PROD    (required reviewer: $ProtectedEnvReviewerTeam)" -ForegroundColor Gray

Write-Host "`n✓ All done! Repository created and configured successfully!" -ForegroundColor Green
Write-Host "`nYou are now in the repository directory on the '$DevelopBranchName' branch." -ForegroundColor Cyan
Write-Host "`nNext steps:" -ForegroundColor Cyan
Write-Host "  1. Start developing!" -ForegroundColor Gray
Write-Host "  2. Configure branch protection rules in GitHub" -ForegroundColor Gray
Write-Host "  3. Set up CI/CD workflows" -ForegroundColor Gray
Write-Host ""
